/* The following code was generated by JFlex 1.7.0 */

package codigo;
import static codigo.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>/home/dioneja/workspace/NewPasquase/src/main/java/codigo/Lexer.flex</tt>
 */
class AnalisadorLexico {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\14\1\17\1\17\1\16\22\0\1\54\1\0\1\41"+
    "\2\0\1\55\1\0\1\42\1\37\1\40\1\60\1\57\1\44\1\61"+
    "\1\43\1\15\12\13\2\0\1\52\1\53\1\51\2\0\10\12\1\27"+
    "\5\12\1\30\13\12\1\47\1\0\1\50\1\56\2\0\1\7\1\26"+
    "\1\31\1\35\1\5\1\6\1\22\1\12\1\24\1\34\1\12\1\10"+
    "\1\23\1\32\1\21\1\20\1\36\1\3\1\11\1\2\1\4\1\33"+
    "\3\12\1\25\1\45\1\1\1\46\7\0\1\17\u1fa2\0\1\17\1\17"+
    "\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\1\3\3\1\4\4\3\1\5\1\6"+
    "\1\7\10\3\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\1"+
    "\1\25\1\26\1\27\1\30\13\3\1\31\1\32\1\0"+
    "\1\1\2\3\1\33\6\3\1\34\2\0\1\35\1\36"+
    "\1\37\1\40\1\41\10\3\1\42\1\43\4\3\1\44"+
    "\10\3\1\45\1\46\1\47\1\50\1\51\6\3\1\52"+
    "\1\3\1\53\4\3\1\54\11\3\1\55\5\3\1\56"+
    "\5\3\1\57\1\3\1\60\1\61\3\3\1\62\1\3"+
    "\1\63\1\64\4\3\1\65\1\3\1\66\1\67\1\3"+
    "\1\70\2\3\1\71\1\72\2\3\1\73\1\74\2\3"+
    "\1\75\1\3\1\76\2\3\1\77";

  private static int [] zzUnpackAction() {
    int [] result = new int[172];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\u012c\0\u015e"+
    "\0\u0190\0\u01c2\0\u01f4\0\u0226\0\62\0\u0258\0\u028a\0\u02bc"+
    "\0\u02ee\0\u0320\0\u0352\0\u0384\0\u03b6\0\u03e8\0\62\0\62"+
    "\0\u041a\0\u044c\0\62\0\62\0\62\0\62\0\62\0\62"+
    "\0\u047e\0\u04b0\0\u04e2\0\u0514\0\62\0\62\0\62\0\62"+
    "\0\u0546\0\u0578\0\u05aa\0\u05dc\0\u060e\0\u0640\0\u0672\0\u06a4"+
    "\0\u06d6\0\u0708\0\u073a\0\u076c\0\u079e\0\u07d0\0\u0802\0\u0834"+
    "\0\u0866\0\226\0\u0898\0\u08ca\0\u08fc\0\u092e\0\u0960\0\u0992"+
    "\0\226\0\u09c4\0\u09f6\0\62\0\62\0\62\0\62\0\62"+
    "\0\u0a28\0\u0a5a\0\u0a8c\0\u0abe\0\u0af0\0\u0b22\0\u0b54\0\u0b86"+
    "\0\226\0\226\0\u0bb8\0\u0bea\0\u0c1c\0\u0c4e\0\u07d0\0\u0c80"+
    "\0\u0cb2\0\u0ce4\0\u0d16\0\u0d48\0\u0d7a\0\u0dac\0\u0dde\0\226"+
    "\0\226\0\62\0\62\0\226\0\u0e10\0\u0e42\0\u0e74\0\u0ea6"+
    "\0\u0ed8\0\u0f0a\0\226\0\u0f3c\0\u0f6e\0\u0fa0\0\u0fd2\0\u1004"+
    "\0\u1036\0\226\0\u1068\0\u109a\0\u10cc\0\u10fe\0\u1130\0\u1162"+
    "\0\u1194\0\u11c6\0\u11f8\0\226\0\u122a\0\u125c\0\u128e\0\u12c0"+
    "\0\u12f2\0\226\0\u1324\0\u1356\0\u1388\0\u13ba\0\u13ec\0\226"+
    "\0\u141e\0\226\0\226\0\u1450\0\u1482\0\u14b4\0\226\0\u14e6"+
    "\0\226\0\226\0\u1518\0\u154a\0\u157c\0\u15ae\0\226\0\u15e0"+
    "\0\226\0\u1612\0\u1644\0\226\0\u1676\0\u16a8\0\226\0\226"+
    "\0\u16da\0\u170c\0\226\0\226\0\u173e\0\u1770\0\226\0\u17a2"+
    "\0\226\0\u17d4\0\u1806\0\226";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[172];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\4\1\14\1\15\1\16\1\3\1\0"+
    "\1\17\1\20\2\4\1\21\1\4\1\22\2\4\1\23"+
    "\1\24\1\25\1\4\1\26\1\4\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\2\1\45\1\46\1\47\1\50"+
    "\63\0\1\3\14\0\1\3\35\0\1\3\7\0\12\4"+
    "\4\0\17\4\25\0\3\4\1\51\6\4\4\0\17\4"+
    "\25\0\1\52\11\4\4\0\17\4\25\0\7\4\1\53"+
    "\2\4\4\0\12\4\1\54\4\4\25\0\2\4\1\55"+
    "\2\4\1\56\4\4\4\0\4\4\1\57\12\4\25\0"+
    "\1\60\1\61\10\4\4\0\17\4\25\0\3\4\1\62"+
    "\6\4\4\0\1\4\1\63\15\4\25\0\3\4\1\64"+
    "\6\4\4\0\17\4\25\0\11\65\1\14\4\0\17\65"+
    "\4\0\1\66\33\0\1\67\46\0\1\4\1\70\3\4"+
    "\1\71\4\4\4\0\17\4\25\0\2\4\1\72\7\4"+
    "\4\0\17\4\25\0\12\4\4\0\12\4\1\73\4\4"+
    "\25\0\12\4\4\0\4\4\1\74\12\4\25\0\5\4"+
    "\1\75\4\4\4\0\1\4\1\76\15\4\25\0\5\4"+
    "\1\77\4\4\4\0\17\4\25\0\5\4\1\100\4\4"+
    "\4\0\17\4\25\0\3\4\1\101\6\4\4\0\17\4"+
    "\25\0\11\102\5\0\17\102\25\0\11\103\5\0\17\103"+
    "\76\0\1\104\57\0\1\105\1\0\1\106\61\0\1\107"+
    "\7\0\1\3\14\0\1\3\35\0\1\3\1\110\6\0"+
    "\5\4\1\111\4\4\4\0\1\112\16\4\25\0\12\4"+
    "\4\0\4\4\1\113\12\4\25\0\12\4\4\0\11\4"+
    "\1\114\5\4\25\0\1\115\11\4\4\0\16\4\1\116"+
    "\25\0\12\4\4\0\12\4\1\117\4\4\25\0\12\4"+
    "\4\0\11\4\1\120\5\4\25\0\12\4\4\0\3\4"+
    "\1\121\13\4\25\0\3\4\1\122\6\4\4\0\17\4"+
    "\25\0\1\4\1\123\10\4\4\0\17\4\25\0\12\4"+
    "\4\0\4\4\1\124\12\4\25\0\12\4\4\0\2\4"+
    "\1\125\14\4\25\0\12\4\4\0\12\4\1\126\4\4"+
    "\25\0\11\65\5\0\17\65\36\0\1\127\46\0\14\67"+
    "\1\0\1\67\2\0\42\67\2\0\12\4\4\0\1\4"+
    "\1\130\15\4\25\0\1\4\1\131\4\4\1\132\3\4"+
    "\4\0\17\4\25\0\1\133\11\4\4\0\4\4\1\134"+
    "\12\4\25\0\12\4\4\0\6\4\1\135\10\4\25\0"+
    "\1\4\1\136\10\4\4\0\17\4\25\0\12\4\4\0"+
    "\12\4\1\137\4\4\25\0\12\4\4\0\1\4\1\140"+
    "\15\4\25\0\1\4\1\141\10\4\4\0\17\4\25\0"+
    "\12\102\4\0\17\102\2\0\1\142\22\0\11\103\5\0"+
    "\17\103\3\0\1\143\21\0\6\4\1\144\3\4\4\0"+
    "\17\4\25\0\12\4\4\0\4\4\1\145\12\4\25\0"+
    "\6\4\1\146\3\4\4\0\17\4\25\0\1\4\1\147"+
    "\10\4\4\0\17\4\25\0\5\4\1\150\4\4\4\0"+
    "\17\4\25\0\2\4\1\151\7\4\4\0\17\4\25\0"+
    "\12\4\4\0\11\4\1\152\5\4\25\0\5\4\1\153"+
    "\4\4\4\0\17\4\25\0\5\4\1\154\4\4\4\0"+
    "\17\4\25\0\5\4\1\155\4\4\4\0\17\4\25\0"+
    "\12\4\4\0\4\4\1\156\12\4\25\0\5\4\1\157"+
    "\4\4\4\0\17\4\25\0\12\4\4\0\2\4\1\160"+
    "\6\4\1\161\5\4\25\0\5\4\1\162\4\4\4\0"+
    "\17\4\25\0\5\4\1\163\4\4\4\0\17\4\25\0"+
    "\3\4\1\164\6\4\4\0\17\4\25\0\12\4\4\0"+
    "\11\4\1\165\5\4\25\0\12\4\4\0\7\4\1\166"+
    "\7\4\25\0\5\4\1\167\4\4\4\0\17\4\25\0"+
    "\7\4\1\170\2\4\4\0\17\4\25\0\1\171\11\4"+
    "\4\0\17\4\25\0\12\4\4\0\4\4\1\172\12\4"+
    "\25\0\3\4\1\173\6\4\4\0\17\4\25\0\12\4"+
    "\4\0\1\4\1\174\15\4\25\0\5\4\1\175\4\4"+
    "\4\0\17\4\25\0\5\4\1\176\4\4\4\0\17\4"+
    "\25\0\12\4\4\0\12\4\1\177\4\4\25\0\6\4"+
    "\1\200\3\4\4\0\17\4\25\0\12\4\4\0\11\4"+
    "\1\201\5\4\25\0\12\4\4\0\1\4\1\202\15\4"+
    "\25\0\1\4\1\203\10\4\4\0\17\4\25\0\3\4"+
    "\1\204\6\4\4\0\17\4\25\0\12\4\4\0\13\4"+
    "\1\205\3\4\25\0\12\4\4\0\4\4\1\206\12\4"+
    "\25\0\12\4\4\0\4\4\1\207\12\4\25\0\12\4"+
    "\4\0\10\4\1\210\6\4\25\0\12\4\4\0\11\4"+
    "\1\211\5\4\25\0\1\212\11\4\4\0\17\4\25\0"+
    "\5\4\1\213\4\4\4\0\17\4\25\0\12\4\4\0"+
    "\5\4\1\214\11\4\25\0\12\4\4\0\13\4\1\215"+
    "\3\4\25\0\12\4\4\0\12\4\1\216\4\4\25\0"+
    "\12\4\4\0\1\4\1\217\15\4\25\0\12\4\4\0"+
    "\14\4\1\220\2\4\25\0\12\4\4\0\12\4\1\221"+
    "\4\4\25\0\12\4\4\0\1\4\1\222\15\4\25\0"+
    "\5\4\1\223\4\4\4\0\17\4\25\0\12\4\4\0"+
    "\15\4\1\224\1\4\25\0\1\4\1\225\10\4\4\0"+
    "\17\4\25\0\1\4\1\226\10\4\4\0\17\4\25\0"+
    "\12\4\4\0\1\4\1\227\15\4\25\0\1\230\11\4"+
    "\4\0\17\4\25\0\3\4\1\231\6\4\4\0\17\4"+
    "\25\0\5\4\1\232\4\4\4\0\17\4\25\0\1\233"+
    "\11\4\4\0\17\4\25\0\12\4\4\0\1\4\1\234"+
    "\15\4\25\0\12\4\4\0\3\4\1\235\13\4\25\0"+
    "\12\4\4\0\4\4\1\236\12\4\25\0\5\4\1\237"+
    "\4\4\4\0\17\4\25\0\12\4\4\0\1\4\1\240"+
    "\15\4\25\0\3\4\1\241\6\4\4\0\17\4\25\0"+
    "\6\4\1\242\3\4\4\0\17\4\25\0\12\4\4\0"+
    "\1\4\1\243\15\4\25\0\5\4\1\244\4\4\4\0"+
    "\17\4\25\0\12\4\4\0\3\4\1\245\13\4\25\0"+
    "\1\4\1\246\10\4\4\0\17\4\25\0\12\4\4\0"+
    "\12\4\1\247\4\4\25\0\3\4\1\250\6\4\4\0"+
    "\17\4\25\0\3\4\1\251\6\4\4\0\17\4\25\0"+
    "\12\4\4\0\12\4\1\252\4\4\25\0\1\253\11\4"+
    "\4\0\17\4\25\0\12\4\4\0\1\4\1\254\15\4"+
    "\23\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6200];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\12\1\1\11\11\1\2\11\2\1\6\11"+
    "\4\1\4\11\15\1\1\0\13\1\2\0\5\11\31\1"+
    "\2\11\111\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[172];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AnalisadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 174) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { /*Ignore*/
            } 
            // fall through
          case 64: break;
          case 2: 
            { lexeme=yytext(); return ERRO;
            } 
            // fall through
          case 65: break;
          case 3: 
            { lexeme=yytext(); return ID;
            } 
            // fall through
          case 66: break;
          case 4: 
            { return E;
            } 
            // fall through
          case 67: break;
          case 5: 
            { lexeme=yytext(); return INTEIRO;
            } 
            // fall through
          case 68: break;
          case 6: 
            { return LINHA;
            } 
            // fall through
          case 69: break;
          case 7: 
            { return DIVISAO;
            } 
            // fall through
          case 70: break;
          case 8: 
            { return ABRE_PARENTESES;
            } 
            // fall through
          case 71: break;
          case 9: 
            { return FECHA_PARENTESES;
            } 
            // fall through
          case 72: break;
          case 10: 
            { return ASPAS_DUPLAS;
            } 
            // fall through
          case 73: break;
          case 11: 
            { return ASPAS_SIMPLES;
            } 
            // fall through
          case 74: break;
          case 12: 
            { return PONTO;
            } 
            // fall through
          case 75: break;
          case 13: 
            { return VIRGULA;
            } 
            // fall through
          case 76: break;
          case 14: 
            { return ABRE_CHAVES;
            } 
            // fall through
          case 77: break;
          case 15: 
            { return FECHA_CHAVES;
            } 
            // fall through
          case 78: break;
          case 16: 
            { return ABRE_COLCHETE;
            } 
            // fall through
          case 79: break;
          case 17: 
            { return FECHA_COLCHETE;
            } 
            // fall through
          case 80: break;
          case 18: 
            { return MAIOR;
            } 
            // fall through
          case 81: break;
          case 19: 
            { return MENOR;
            } 
            // fall through
          case 82: break;
          case 20: 
            { return ATRIBUICAO;
            } 
            // fall through
          case 83: break;
          case 21: 
            { return POTENCIA;
            } 
            // fall through
          case 84: break;
          case 22: 
            { return SOMA;
            } 
            // fall through
          case 85: break;
          case 23: 
            { return MULTIPLICACAO;
            } 
            // fall through
          case 86: break;
          case 24: 
            { return SUBTRACAO;
            } 
            // fall through
          case 87: break;
          case 25: 
            { return SE;
            } 
            // fall through
          case 88: break;
          case 26: 
            { lexeme=yytext(); return ID_INVALIDO;
            } 
            // fall through
          case 89: break;
          case 27: 
            { return OU;
            } 
            // fall through
          case 90: break;
          case 28: 
            { return DE;
            } 
            // fall through
          case 91: break;
          case 29: 
            { return MAIOR_IGUAL;
            } 
            // fall through
          case 92: break;
          case 30: 
            { return DIFERENTE;
            } 
            // fall through
          case 93: break;
          case 31: 
            { return MENOR_IGUAL;
            } 
            // fall through
          case 94: break;
          case 32: 
            { return IGUALDADE;
            } 
            // fall through
          case 95: break;
          case 33: 
            { return RESTO_DIVISAO;
            } 
            // fall through
          case 96: break;
          case 34: 
            { return FIM;
            } 
            // fall through
          case 97: break;
          case 35: 
            { return ATE;
            } 
            // fall through
          case 98: break;
          case 36: 
            { lexeme=yytext(); return REAL;
            } 
            // fall through
          case 99: break;
          case 37: 
            { return NAO;
            } 
            // fall through
          case 100: break;
          case 38: 
            { return VAR;
            } 
            // fall through
          case 101: break;
          case 39: 
            { lexeme=yytext(); return PALAVRA;
            } 
            // fall through
          case 102: break;
          case 40: 
            { lexeme=yytext(); return CARACTERE;
            } 
            // fall through
          case 103: break;
          case 41: 
            { return REAL;
            } 
            // fall through
          case 104: break;
          case 42: 
            { return FACA;
            } 
            // fall through
          case 105: break;
          case 43: 
            { return LEIA;
            } 
            // fall through
          case 106: break;
          case 44: 
            { return PARA;
            } 
            // fall through
          case 107: break;
          case 45: 
            { return ENTAO;
            } 
            // fall through
          case 108: break;
          case 46: 
            { return SENAO;
            } 
            // fall through
          case 109: break;
          case 47: 
            { return BIB_IO;
            } 
            // fall through
          case 110: break;
          case 48: 
            { return CONST;
            } 
            // fall through
          case 111: break;
          case 49: 
            { return REPITA;
            } 
            // fall through
          case 112: break;
          case 50: 
            { return FUNCAO;
            } 
            // fall through
          case 113: break;
          case 51: 
            { return LEIA_LN;
            } 
            // fall through
          case 114: break;
          case 52: 
            { return LOGICO;
            } 
            // fall through
          case 115: break;
          case 53: 
            { return INICIO;
            } 
            // fall through
          case 116: break;
          case 54: 
            { return UTILIZE;
            } 
            // fall through
          case 117: break;
          case 55: 
            { return ESCREVA;
            } 
            // fall through
          case 118: break;
          case 56: 
            { return ARRANJO;
            } 
            // fall through
          case 119: break;
          case 57: 
            { return PALAVRA;
            } 
            // fall through
          case 120: break;
          case 58: 
            { return INTEIRO;
            } 
            // fall through
          case 121: break;
          case 59: 
            { return ENQUANTO;
            } 
            // fall through
          case 122: break;
          case 60: 
            { return PROGRAMA;
            } 
            // fall through
          case 123: break;
          case 61: 
            { return ESCREVA_LN;
            } 
            // fall through
          case 124: break;
          case 62: 
            { return CARACTERE;
            } 
            // fall through
          case 125: break;
          case 63: 
            { return PROCEDIMENTO;
            } 
            // fall through
          case 126: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
