
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 05 22:56:36 BRT 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  public static final int ABRE_CHAVES = 41;
  public static final int ABRE_COLCHETES = 43;
  public static final int ABRE_PARENTESES = 35;
  public static final int AGRUPAMENTO = 60;
  public static final int ATE = 26;
  public static final int ASPAS_DUPLAS = 37;
  public static final int ASPAS_SIMPLES = 38;
  public static final int ATRIBUICAO = 52;
  public static final int BIB_IO = 6;
  public static final int BRANCO = 59;
  public static final int CARACTERE = 12;
  public static final int CONST = 7;
  public static final int DE = 25;
  public static final int DIFERENTE = 47;
  public static final int DIVISAO = 57;
  public static final int EOF = 0;
  public static final int ENQUANTO = 28;
  public static final int ENTAO = 22;
  public static final int ERRO = 3;
  public static final int ESCREVA = 19;
  public static final int ESCREVA_LN = 20;
  public static final int FACA = 27;
  public static final int FECHA_CHAVES = 42;
  public static final int FECHA_COLCHETES = 44;
  public static final int FECHA_PARENTESES = 36;
  public static final int FUNCAO = 31;
  public static final int ID = 58;
  public static final int ID_INVALIDO = 2;
  public static final int IGUALDADE = 53;
  public static final int INICIO = 8;
  public static final int INTEIRO = 10;
  public static final int LEIA = 17;
  public static final int LEIA_LN = 18;
  public static final int LINHA = 1;
  public static final int LOGICO = 14;
  public static final int MAIOR = 45;
  public static final int MAIOR_IGUAL = 49;
  public static final int MENOR = 46;
  public static final int MENOR_IGUAL = 48;
  public static final int MULTIPLICACAO = 55;
  public static final int NAO = 34;
  public static final int NUMERO = 64;
  public static final int OU = 32;
  public static final int OPERADORES_ATRIBUICAO = 63;
  public static final int OPERADORES_LOGICOS = 62;
  public static final int PALAVRA = 13;
  public static final int PARA = 24;
  public static final int PONTO = 39;
  public static final int POTENCIA = 51;
  public static final int PROCEDIMENTO = 30;
  public static final int PROGRAMA = 4;
  public static final int REAL = 11;
  public static final int OPERADORES_RELACIONAIS = 61;
  public static final int PONTO_VIRGULA = 65;
  public static final int REPITA = 29;
  public static final int RESTO_DIVISAO = 50;
  public static final int SE = 21;
  public static final int SENAO = 23;
  public static final int SOMA = 54;
  public static final int SUBTRACAO = 56;
  public static final int TIPO_DADO = 60;
  public static final int UTILIZE = 5;
  public static final int VAR = 15;
  public static final int VIRGULA = 40;
}

