
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 12 22:08:19 BRT 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 35;
  public static final int Llave_c = 44;
  public static final int Op_booleano = 40;
  public static final int Llave_a = 43;
  public static final int If = 24;
  public static final int atribuicao = 18;
  public static final int programa = 8;
  public static final int Inteiro = 36;
  public static final int T_dato = 21;
  public static final int Real = 37;
  public static final int pv = 3;
  public static final int inteiro = 9;
  public static final int tipo_dado = 13;
  public static final int Else = 25;
  public static final int bibIO = 2;
  public static final int Corchete_c = 46;
  public static final int Corchete_a = 45;
  public static final int real = 10;
  public static final int pf = 7;
  public static final int dois_pontos = 14;
  public static final int While = 27;
  public static final int Division = 33;
  public static final int Int = 22;
  public static final int Parentesis_c = 42;
  public static final int Cadena = 23;
  public static final int Parentesis_a = 41;
  public static final int For = 28;
  public static final int var = 12;
  public static final int P_coma = 48;
  public static final int EOF = 0;
  public static final int funcao = 16;
  public static final int error = 1;
  public static final int procedimento = 17;
  public static final int Linea = 19;
  public static final int Op_atribucion = 38;
  public static final int ERROR = 51;
  public static final int Do = 26;
  public static final int id = 49;
  public static final int Op_logico = 34;
  public static final int utilize = 4;
  public static final int virgula = 15;
  public static final int fim = 6;
  public static final int Resta = 31;
  public static final int ini = 5;
  public static final int Multiplicacion = 32;
  public static final int constante = 11;
  public static final int Op_incremento = 39;
  public static final int Numero = 50;
  public static final int Suma = 30;
  public static final int Main = 47;
  public static final int Igual = 29;
  public static final int Comillas = 20;
}

